title: "Indie Open Source"
description: "open source for solo hackers and small firms"
url: "https://indieopensource.com"
homepage: "https://indieopensource.com"
repository: "indieopensource/indieopensource.github.io"
repository_url: "https://github.com/indieopensource/indieopensource.github.io"
collections:
  indies:
    output: true
  models:
    output: true
  forms:
    output: true
  indie_guides:
    output: true
  user_guides:
    output: true
  contributor_guides:
    output: true
exclude:
- Gemfile
- Gemfile.lock
- README.md
